codecov:
  require_ci_to_pass: true

comment:
  layout: "diff, files, header, footer"
  behavior: default

coverage:
  precision: 2
  round: down
  range: 80..100
  status:
    project:
      default:
        target: auto
        threshold: 4%
    patch:
      default:
        target: 80%
        threshold: 4%
        informational: true

flag_management:
  default_rules:
    carryforward: true

ignore:
  - "**/tests/**"
  - "contracts/src/denshokan.cairo"
  - "contracts/src/minigame_registry.cairo"

github_checks:
  annotations: false
