[package]
name = "denshokan_registry"
version = "0.1.0"
edition.workspace = true
cairo-version.workspace = true

[dependencies]
starknet.workspace = true
game_components_embeddable_game_standard.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_token.workspace = true
openzeppelin_interfaces.workspace = true

[dev-dependencies]
snforge_std.workspace = true
denshokan_testing.workspace = true
denshokan_token.workspace = true
denshokan_renderer.workspace = true
game_components_test_common.workspace = true


[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "denshokan_token::denshokan::Denshokan",
    "denshokan_renderer::default_renderer::DefaultRenderer",
    "game_components_test_common::mocks::minigame_mock::minigame_mock",
]

[lib]
name = "denshokan_registry"
