[package]
name = "denshokan_token"
version = "0.1.0"
edition.workspace = true
cairo-version.workspace = true

[dependencies]
starknet.workspace = true
denshokan_interfaces.workspace = true
denshokan_renderer.workspace = true
game_components_embeddable_game_standard.workspace = true
game_components_utilities.workspace = true

openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_interfaces.workspace = true
openzeppelin_access.workspace = true

[dev-dependencies]
snforge_std.workspace = true
denshokan_testing.workspace = true
denshokan_registry.workspace = true
denshokan_renderer.workspace = true
game_components_test_common.workspace = true


[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "denshokan_registry::minigame_registry::MinigameRegistry",
    "denshokan_renderer::default_renderer::DefaultRenderer",
    "game_components_test_common::mocks::minigame_mock::minigame_mock",
]

[lib]
name = "denshokan_token"
